### PR TITLE
Add coordinate columns

### PR DESCRIPTION
**Pull request by christensenmichael0**
@Bobfrat this is ready for some initial testing... I still need to truncate the coordinates. Working on that now.

### CODE REVIEW

**Comment by Bobfrat** [comment]
👍  Nice, does it work with the station markers as well (NDBC, CDIP, CO-OPS etc)? And you tested with time series and profiles?

**Comment by christensenmichael0** [comment]
I'll test with stations now. Timeseries and profiles seem to be working.

**Comment by christensenmichael0** [comment]
@Bobfrat made an update in the OM PR. So this should be working for stations now as well.

**Comment by christensenmichael0** [comment]
@Bobfrat this is ready for merging. I'll need to update the commit hash in OM (bower.json) to point to this latest commit before merging changes into the OM master branch.

**Pull request merged**
